version: "3.9"

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8081:80" # Map port 8081 on the host to port 80 in the container
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress-network
    deploy:
      replicas: 2 # Start with 2 replicas
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress-network

networks:
  wordpress-network:
    driver: overlay

volumes:
  db_data:
