version: '3.8'

services:
  game-logic:
    build:
      context: .
      dockerfile: Dockerfile.game_logic
    ports:
      - "5100:5000"

  user-interaction:
    build:
      context: .
      dockerfile: Dockerfile.user_interaction
    ports:
      - "5101:5001"

  real-time-updates:
    build:
      context: .
      dockerfile: Dockerfile.real_time_updates
    ports:
      - "5102:5002"