version: "3.8"

services:
  flask_app:
    build:
      context: .
    image: flask-swarm-demo:latest
    ports:
      - "5000:5000"
    networks:
      - app-net
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

networks:
  app-net:
    external: true
