name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-swarm-demo:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-swarm-demo:latest

    - name: Deploy to Swarm
      run: |
        docker service update \
          --image jenkins/jenkins:lts \
          jenkins_service
